//
// Created by Жезл on 16.03.2023.
//

#ifndef MAC_SAMOVAR_CODES_HPP
#define MAC_SAMOVAR_CODES_HPP

enum {
    SERVER_START,
    SERVER_SETUP,
    SERVER_STOP,
    SERVER_STOPPED,
    SERVER_ALREADY_RUN,
    SERVER_RUNNING_ERROR,
    SERVER_STOPPING_ERROR,
    SERVER_NOT_RUNNING,
    TRIGGER_NOT_FOUND,
};

#endif //MAC_SAMOVAR_CODES_HPP
