### Send POST request install update
POST https://router.zeleza.ru:11133/kvas/v1/let_install
Content-Type: application/json

{
  "app_name": "kvas"
}

### Send POST request check for update
POST https://router.zeleza.ru:11133/kvas/v1/check_update
Content-Type: application/json

{
  "app_name": "kvas"
}

### Send POST request get_app_history
POST https://router.zeleza.ru:11133/kvas/v1/get_app_history
Content-Type: application/json

{
  "app_name": "kvas"
}


### Send POST request get_router_data
POST https://router.zeleza.ru:11133/kvas/v1/get_router_data
Content-Type: application/json

### Send POST request get_apps_data
POST https://router.zeleza.ru:11133/kvas/v1/get_apps_data
Content-Type: application/json

