
POST https://api.zeleza.ru:11211/api/v1/get_rating
Content-Type: application/json

{
  "app_name": "kvas"
}



### Send GET request get_rating
POST https://api.zeleza.ru:11211/api/v1/get_rating
Content-Type: application/json

{
  "app_name": "samovar"
}

### Send GET request new_record
POST https://api.zeleza.ru:11211/api/v1/new_record
Content-Type: application/json

{
  "app_name": "kvas",
  "version": "1.3",
  "name": "Bob",
  "email": "test@email.cc",
  "review": "Тестовый отзыв: программа отличная так держать! Супер",
  "rating": "9",
  "type": "Отзыв с рейтингом",
  "device_id": "42csr4rc435v34v2c5tc2",
  "processor": "mipsel",
  "model": "Ultra KN-3118"
}

### Send POST request reviews_list
POST https://api.zeleza.ru:11211/api/v1/reviews_list
Content-Type: application/json

{
  "app_name": "samovar",
  "version": "latest"
}

### Send GET request reviews_table_page
GET https://api.zeleza.ru:11211/api/v1/reviews_table_page?key=secret_key&app_name=samovar

### Send GET request summary_table_page
GET https://api.zeleza.ru:11211/api/v1/summary_table_page?key=secret_key


